fixtures:
  symlinks:
    "gitlab": "#{source_dir}"
  repositories:
    "rbenv": "git://github.com/alup/puppet-rbenv.git"
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "vcsrepo": "git://github.com/puppetlabs/puppetlabs-vcsrepo.git"
